export default {
  sounds: {
    infoPopUpOpen: new AudioClip("sounds/navigationForwardSelection.mp3"),
    infoPopUpClose: new AudioClip("sounds/navigationBackSelection.mp3"),
  },
  models: {
    building: new GLTFShape("models/building.glb"),
  },
  artwork: {
    brideOfFrankenstein: new GLTFShape("artworks/brideOfFrankenstein.gltf"),
    backFromJapan: new GLTFShape("artworks/backFromJapan.gltf"),
    fckAllYall: new GLTFShape("artworks/fckAllYall.gltf"),
    mariaB: new GLTFShape("artworks/mariaB.gltf"),
    theGirlWithVR: new GLTFShape("artworks/theGirlWithVR.gltf"),
    dreams: new GLTFShape("artworks/dreams.gltf"),
    cyberpunkCatwalk: new GLTFShape("artworks/cyberpunkCatwalk.gltf"),
    postApocalypticLovers: new GLTFShape("artworks/postApocalypticLovers.gltf"),
    theTraveller: new GLTFShape("artworks/theTraveller.gltf"),
    virtualRealityOnTheStreets: new GLTFShape("artworks/virtualRealityOnTheStreets.gltf"),
    mysticWeb: new GLTFShape("artworks/mysticWeb.gltf"),
    altcoinFoundersPlayingPool: new GLTFShape("artworks/altcoinFoundersPlayingPool.gltf"),
    beautyMask: new GLTFShape("artworks/beautyMask.gltf"),
    jessicaJones: new GLTFShape("artworks/jessicaJones.gltf"),
    weWillFigureItOut: new GLTFShape("artworks/weWillFigureItOut.gltf"),
    glitch0MC18: new GLTFShape("artworks/glitch0MC18.gltf"),
    glitch0FL43: new GLTFShape("artworks/glitch0FL43.gltf"),
    glitch0FY21: new GLTFShape("artworks/glitch0FY21.gltf"),
    glitch0MC40: new GLTFShape("artworks/glitch0MC40.gltf"),
    glitch0UW22: new GLTFShape("artworks/glitch0UW22.gltf"),
    ganoodle10362: new GLTFShape("artworks/ganoodle10362.gltf"),
    godsOfRock: new GLTFShape("artworks/godsOfRock.gltf"),
    evenTheMostBeautifulHeartCanSting: new GLTFShape("artworks/evenTheMostBeautifulHeartCanSting.gltf"),
    treeOfLust: new GLTFShape("artworks/treeOfLust.gltf"),
    planetCovid: new GLTFShape("artworks/planetCovid.gltf"),
    airDrop: new GLTFShape("artworks/airDrop.gltf"),
    bitcoinMooning: new GLTFShape("artworks/bitcoinMooning.gltf"),
    proofOfSteak: new GLTFShape("artworks/proofOfSteak.gltf"),
    whaleShares: new GLTFShape("artworks/whaleShares.gltf"),
    filter: new GLTFShape("artworks/filter.gltf"),
    tuneIn: new GLTFShape("artworks/tuneIn.gltf"),
    anonMouse: new GLTFShape("artworks/anonMouse.gltf"),
    renaissanceIsNow: new GLTFShape("artworks/renaissanceIsNow.gltf"),
    bTheChange: new GLTFShape("artworks/bTheChange.gltf"),
    baronBitcoin: new GLTFShape("artworks/baronBitcoin.gltf"),
    metaCanned: new GLTFShape("artworks/metaCanned.gltf"),
  },
  textures: {
    brideOfFrankensteinInfo: new Texture("images/brideOfFrankensteinInfo.png"),
    backFromJapanInfo: new Texture("images/backFromJapanInfo.png"),
    fckAllYallInfo: new Texture("images/fckAllYallInfo.png"),
    mariaBInfo: new Texture("images/mariaBInfo.png"),
    theGirlWithVRInfo: new Texture("images/theGirlWithVRInfo.png"),
    dreamsInfo: new Texture("images/dreamsInfo.png"),
    cyberpunkCatwalkInfo: new Texture("images/cyberpunkCatwalkInfo.png"),
    postApocalypticLoversInfo: new Texture("images/postApocalypticLoversInfo.png"),
    theTravellerInfo: new Texture("images/theTravellerInfo.png"),
    virtualRealityOnTheStreetsInfo: new Texture("images/virtualRealityOnTheStreetsInfo.png"),
    mysticWebInfo: new Texture("images/mysticWebInfo.png"),
    altcoinFoundersPlayingPoolInfo: new Texture("images/altcoinFoundersPlayingPoolInfo.png"),
    beautyMaskInfo: new Texture("images/beautyMaskInfo.png"),
    jessicaJonesInfo: new Texture("images/jessicaJonesInfo.png"),
    weWillFigureItOutInfo: new Texture("images/weWillFigureItOutInfo.png"),
    glitch0MC18Info: new Texture("images/glitch0MC18Info.png"),
    glitch0FL43Info: new Texture("images/glitch0FL43Info.png"),
    glitch0FY21Info: new Texture("images/glitch0FY21Info.png"),
    glitch0MC40Info: new Texture("images/glitch0MC40Info.png"),
    glitch0UW22Info: new Texture("images/glitch0UW22Info.png"),
    ganoodle10362Info: new Texture("images/ganoodle10362Info.png"),
    godsOfRockInfo: new Texture("images/godsOfRockInfo.png"),
    evenTheMostBeautifulHeartCanStingInfo: new Texture("images/evenTheMostBeautifulHeartCanStingInfo.png"),
    treeOfLustInfo: new Texture("images/treeOfLustInfo.png"),
    planetCovidInfo: new Texture("images/planetCovidInfo.png"),
    airDropInfo: new Texture("images/airDropInfo.png"),
    bitcoinMooningInfo: new Texture("images/bitcoinMooningInfo.png"),
    proofOfSteakInfo: new Texture("images/proofOfSteakInfo.png"),
    whaleSharesInfo: new Texture("images/whaleSharesInfo.png"),
    filterInfo: new Texture("images/filterInfo.png"),
    tuneInInfo: new Texture("images/tuneInInfo.png"),
    anonMouseInfo: new Texture("images/anonMouseInfo.png"),
    renaissanceIsNowInfo: new Texture("images/renaissanceIsNowInfo.png"),
    bTheChangeInfo: new Texture("images/bTheChangeInfo.png"),
    baronBitcoinInfo: new Texture("images/baronBitcoinInfo.png"),
    metaCannedInfo: new Texture("images/metaCannedInfo.png"),
    closeButton: new Texture("images/closeButton.png"),
    buyButton: new Texture("images/buyButton.png"),
  },
}
